const options = [
  { value: "java", label: "Java" },
  { value: "cpp", label: "Cpp" },
  { value: "javascript", label: "Javascript" },
  { value: "c", label: "C" },
  { value: "python", label: "Python" },
  { value: "jsx", label: "JSX" },
  { value: "bash", label: "Bash" },
  { value: "ruby", label: "Ruby" },
  { value: "php", label: "PHP" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "objective-c", label: "Objective-C" },
  { value: "scala", label: "Scala" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "typescript", label: "TypeScript" },
  { value: "vue", label: "Vue" },
  { value: "react", label: "React" },
  { value: "angular", label: "Angular" },
  { value: "django", label: "Django" },
  { value: "flask", label: "Flask" },
  { value: "laravel", label: "Laravel" },
  { value: "symfony", label: "Symfony" },
  { value: "express", label: "Express" },
  { value: "spring", label: "Spring" },
  { value: "hibernate", label: "Hibernate" },
  { value: "mysql", label: "MySQL" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "mongodb", label: "MongoDB" },
  { value: "redis", label: "Redis" },
  { value: "graphql", label: "GraphQL" },
  { value: "apollo", label: "Apollo" },
  { value: "jest", label: "Jest" },
  { value: "mocha", label: "Mocha" },
  { value: "chai", label: "Chai" },
  { value: "sinon", label: "Sinon" },
  { value: "webpack", label: "Webpack" },
  { value: "gulp", label: "Gulp" },
  { value: "grunt", label: "Grunt" },
  { value: "npm", label: "NPM" },
  { value: "yarn", label: "Yarn" },
  { value: "babel", label: "Babel" },
  { value: "eslint", label: "ESLint" },
  { value: "prettier", label: "Prettier" },
  { value: "webpack-dev-server", label: "Webpack Dev Server" },
  { value: "nodemon", label: "Nodemon" },
  { value: "pm2", label: "PM2" },
  { value: "nginx", label: "Nginx" },
  { value: "apache", label: "Apache" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "terraform", label: "Terraform" },
  { value: "ansible", label: "Ansible" },
  { value: "jenkins", label: "Jenkins" },
  { value: "travis-ci", label: "Travis CI" },
  { value: "circle-ci", label: "Circle CI" },
  { value: "gitlab-ci", label: "GitLab CI" },
  { value: "aws", label: "AWS" },
  { value: "azure", label: "Azure" },
  { value: "google-cloud", label: "Google Cloud" },
  { value: "firebase", label: "Firebase" },
  { value: "heroku", label: "Heroku" },
  { value: "digitalocean", label: "DigitalOcean" },
  { value: "netlify", label: "Netlify" },
  { value: "vercel", label: "Vercel" },
  { value: "next.js", label: "Next.js" },
  { value: "gatsby", label: "Gatsby" },
  { value: "nuxt.js", label: "Nuxt.js" },
  { value: "storybook", label: "Storybook" },
  { value: "styled-components", label: "Styled Components" },
  { value: "tailwind-css", label: "Tailwind CSS" },
  { value: "bootstrap", label: "Bootstrap" },
  { value: "material-ui", label: "Material UI" },
  { value: "ant-design", label: "Ant Design" },
  { value: "bulma", label: "Bulma" },
  { value: "foundation", label: "Foundation" },
  { value: "semantic-ui", label: "Semantic UI" },
  { value: "react-bootstrap", label: "React Bootstrap" },
  { value: "react-router", label: "React Router" },
  { value: "vue-router", label: "Vue Router" },
  { value: "react-redux", label: "React Redux" },
  { value: "mobx", label: "MobX" },
  { value: "redux-saga", label: "Redux Saga" },
  { value: "redux-thunk", label: "Redux Thunk" },
  { value: "vuex", label: "Vuex" },
  { value: "apollo-client", label: "Apollo Client" },
  { value: "react-native", label: "React Native" },
  { value: "ionic", label: "Ionic" },
  { value: "cordova", label: "Cordova" },
  { value: "electron", label: "Electron" },
  { value: "jest", label: "Jest" },
  { value: "enzyme", label: "Enzyme" },
  { value: "cypress", label: "Cypress" },
  { value: "nightwatch", label: "Nightwatch" },
  { value: "protractor", label: "Protractor" },
  { value: "jest-puppeteer", label: "Jest Puppeteer" },
  { value: "framer-motion", label: "Framer Motion" },
  { value: "gsap", label: "GSAP" },
  { value: "three.js", label: "Three.js" },
  { value: "d3.js", label: "D3.js" },
  { value: "chart.js", label: "Chart.js" },
  { value: "highcharts", label: "Highcharts" },
  { value: "leaflet", label: "Leaflet" },
  { value: "mapbox", label: "Mapbox" },
  { value: "socket.io", label: "Socket.io" },
  { value: "graphql", label: "GraphQL" },
  { value: "rest", label: "REST" },
  { value: "axios", label: "Axios" },
  { value: "fetch", label: "Fetch" },
  { value: "lodash", label: "Lodash" },
  { value: "ramda", label: "Ramda" },
  { value: "moment.js", label: "Moment.js" },
  { value: "date-fns", label: "date-fns" },
  { value: "regex", label: "RegEx" },
  { value: "babel", label: "Babel" },
  { value: "webpack", label: "Webpack" },
  { value: "rollup", label: "Rollup" },
  { value: "gulp", label: "Gulp" },
  { value: "grunt", label: "Grunt" },
  { value: "parcel", label: "Parcel" },
  { value: "babel-loader", label: "Babel Loader" },
  { value: "eslint", label: "ESLint" },
  { value: "prettier", label: "Prettier" },
  { value: "stylelint", label: "Stylelint" },
  { value: "webpack-dev-server", label: "Webpack Dev Server" },
  { value: "graph", label: "Graph" },
  { value: "bfs", label: "BFS" },
  { value: "dfs", label: "DFS" },
  { value: "dijkstra", label: "Dijkstra" },
  { value: "Array", label: "Array" },
  { value: "Stack", label: "Stack" },
  { value: "linked-list", label: "LinkedList" },
  { value: "binary-tree", label: "BinaryTree" },
  { value: "hash-table", label: "HashTable" },
  { value: "queue", label: "Queue" },
  { value: "heap", label: "Heap" },
  { value: "merge-sort", label: "MergeSort" },
  { value: "quick-sort", label: "QuickSort" },
  { value: "binary-search", label: "BinarySearch" },
  { value: "insertion-sort", label: "InsertionSort" },
  { value: "selection-sort", label: "SelectionSort" },
  { value: "bubble-sort", label: "BubbleSort" },
  { value: "linear-search", label: "LinearSearch" },
  { value: "trie", label: "Trie" },
  { value: "avl-tree", label: "AVLTree" },
  { value: "red-black-tree", label: "RedBlackTree" },
  { value: "heap-sort", label: "HeapSort" },
  { value: "shell-sort", label: "ShellSort" },
  { value: "bucket-sort", label: "BucketSort" },
  { value: "radix-sort", label: "RadixSort" },
  { value: "counting-sort", label: "CountingSort" },
  { value: "topological-sort", label: "TopologicalSort" },
  { value: "bellman-ford", label: "BellmanFord" },
  { value: "floyd-warshall", label: "FloydWarshall" },
  { value: "kruskal", label: "Kruskal" },
  { value: "prim", label: "Prim" },
  { value: "union-find", label: "UnionFind" },
  { value: "sieve-of-eratosthenes", label: "SieveOfEratosthenes" },
  { value: "sieve-of-atkin", label: "SieveOfAtkin" },
  { value: "euclidean-algorithm", label: "EuclideanAlgorithm" },
  {
    value: "extended-euclidean-algorithm",
    label: "ExtendedEuclideanAlgorithm",
  },
  { value: "factorial", label: "Factorial" },
  { value: "fibonacci", label: "Fibonacci" },
  { value: "lcm", label: "LCM" },
  { value: "gcd", label: "GCD" },
  { value: "power-set", label: "PowerSet" },
  { value: "subsets-with-sum", label: "SubsetsWithSum" },
  {
    value: "longest-common-substring",
    label: "LongestCommonSubstring",
  },
  {
    value: "longest-palindromic-substring",
    label: "LongestPalindromicSubstring",
  },
  {
    value: "longest-increasing-subsequence",
    label: "LongestIncreasingSubsequence",
  },
  { value: "edit-distance", label: "EditDistance" },
  { value: "knapsack-problem", label: "KnapsackProblem" },
  {
    value: "travelling-salesman-problem",
    label: "TravellingSalesmanProblem",
  },
  { value: "maximum-flow", label: "MaximumFlow" },
  { value: "minimum-cut", label: "MinimumCut" },
  {
    value: "strongly-connected-components",
    label: "StronglyConnectedComponents",
  },
  { value: "minimum-spanning-tree", label: "MinimumSpanningTree" },
  { value: "hamiltonian-cycle", label: "HamiltonianCycle" },
  { value: "bipartite-matching", label: "BipartiteMatching" },
  { value: "kmp", label: "KMP" },
  { value: "rabin-karp", label: "RabinKarp" },
  { value: "z-algorithm", label: "ZAlgorithm" },
  { value: "segment-tree", label: "SegmentTree" },
  { value: "fenwick-tree", label: "FenwickTree" },
  { value: "suffix-tree", label: "SuffixTree" },
  { value: "tries", label: "Tries" },
  { value: "splay-tree", label: "SplayTree" },
  { value: "skip-list", label: "SkipList" },
  { value: "circular-queue", label: "CircularQueue" },
  { value: "deque", label: "Deque" },
  { value: "circular-linked-list", label: "CircularLinkedList" },
  { value: "binary-search-tree", label: "BinarySearchTree" },
  { value: "minimum-heap", label: "MinimumHeap" },
  { value: "maximum-heap", label: "MaximumHeap" },
  { value: "heap", label: "Heap" },
  { value: "disjoint-set", label: "DisjointSet" },
  { value: "typing", label: "Typing" },
  { value: "postman", label: "Postman" },
  { value: "mongodb", label: "MongoDB" },
];

export default options;
